services:
  postgres:
    image: postgres:17-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - bookshop_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=bookshop_user
      - POSTGRES_DB=bookshop_db

volumes:
  bookshop_postgres:

